

hello: hello.o greeting.o factorial.o
	gcc hello.o greeting.o factorial.o -o hello

hello.o: hello.c
	gcc -Wall -c hello.c

greeting.o: greeting.c
	gcc -Wall -c greeting.c

factorial.o: factorial.c
	gcc -Wall -c factorial.c


#TARGET: PREREQ1 PREREQ2 ....
#	COMMAND





